//------------------------------------------------------------------------------
// <auto-generated>
//     이 코드는 도구를 사용하여 생성되었습니다.
//     런타임 버전:4.0.30319.42000
//
//     파일 내용을 변경하면 잘못된 동작이 발생할 수 있으며, 코드를 다시 생성하면
//     이러한 변경 내용이 손실됩니다.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 이 소스 코드가 Microsoft.VSDesigner, 버전 4.0.30319.42000에서 자동으로 생성되었습니다.
// 
#pragma warning disable 1591

namespace insert.soapclient {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="device_tokenSoap", Namespace="http://tempuri.org/")]
    public partial class device_token : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback HelloWorldOperationCompleted;
        
        private System.Threading.SendOrPostCallback tokenOperationCompleted;
        
        private System.Threading.SendOrPostCallback potal_version_checkOperationCompleted;
        
        private System.Threading.SendOrPostCallback barcode_version_checkOperationCompleted;
        
        private System.Threading.SendOrPostCallback product_getOperationCompleted;
        
        private System.Threading.SendOrPostCallback product_outOperationCompleted;
        
        private System.Threading.SendOrPostCallback product_check_tolocationOperationCompleted;
        
        private System.Threading.SendOrPostCallback product_checkOperationCompleted;
        
        private System.Threading.SendOrPostCallback productOperationCompleted;
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public device_token() {
            this.Url = global::insert.Properties.Settings.Default.insert_soapclient_device_token;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event HelloWorldCompletedEventHandler HelloWorldCompleted;
        
        /// <remarks/>
        public event tokenCompletedEventHandler tokenCompleted;
        
        /// <remarks/>
        public event potal_version_checkCompletedEventHandler potal_version_checkCompleted;
        
        /// <remarks/>
        public event barcode_version_checkCompletedEventHandler barcode_version_checkCompleted;
        
        /// <remarks/>
        public event product_getCompletedEventHandler product_getCompleted;
        
        /// <remarks/>
        public event product_outCompletedEventHandler product_outCompleted;
        
        /// <remarks/>
        public event product_check_tolocationCompletedEventHandler product_check_tolocationCompleted;
        
        /// <remarks/>
        public event product_checkCompletedEventHandler product_checkCompleted;
        
        /// <remarks/>
        public event productCompletedEventHandler productCompleted;
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/HelloWorld", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string HelloWorld() {
            object[] results = this.Invoke("HelloWorld", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void HelloWorldAsync() {
            this.HelloWorldAsync(null);
        }
        
        /// <remarks/>
        public void HelloWorldAsync(object userState) {
            if ((this.HelloWorldOperationCompleted == null)) {
                this.HelloWorldOperationCompleted = new System.Threading.SendOrPostCallback(this.OnHelloWorldOperationCompleted);
            }
            this.InvokeAsync("HelloWorld", new object[0], this.HelloWorldOperationCompleted, userState);
        }
        
        private void OnHelloWorldOperationCompleted(object arg) {
            if ((this.HelloWorldCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.HelloWorldCompleted(this, new HelloWorldCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/token", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string token([System.Xml.Serialization.XmlElementAttribute("token")] string token1) {
            object[] results = this.Invoke("token", new object[] {
                        token1});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tokenAsync(string token1) {
            this.tokenAsync(token1, null);
        }
        
        /// <remarks/>
        public void tokenAsync(string token1, object userState) {
            if ((this.tokenOperationCompleted == null)) {
                this.tokenOperationCompleted = new System.Threading.SendOrPostCallback(this.OntokenOperationCompleted);
            }
            this.InvokeAsync("token", new object[] {
                        token1}, this.tokenOperationCompleted, userState);
        }
        
        private void OntokenOperationCompleted(object arg) {
            if ((this.tokenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tokenCompleted(this, new tokenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/potal_version_check", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string potal_version_check() {
            object[] results = this.Invoke("potal_version_check", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void potal_version_checkAsync() {
            this.potal_version_checkAsync(null);
        }
        
        /// <remarks/>
        public void potal_version_checkAsync(object userState) {
            if ((this.potal_version_checkOperationCompleted == null)) {
                this.potal_version_checkOperationCompleted = new System.Threading.SendOrPostCallback(this.Onpotal_version_checkOperationCompleted);
            }
            this.InvokeAsync("potal_version_check", new object[0], this.potal_version_checkOperationCompleted, userState);
        }
        
        private void Onpotal_version_checkOperationCompleted(object arg) {
            if ((this.potal_version_checkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.potal_version_checkCompleted(this, new potal_version_checkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/barcode_version_check", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string barcode_version_check() {
            object[] results = this.Invoke("barcode_version_check", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void barcode_version_checkAsync() {
            this.barcode_version_checkAsync(null);
        }
        
        /// <remarks/>
        public void barcode_version_checkAsync(object userState) {
            if ((this.barcode_version_checkOperationCompleted == null)) {
                this.barcode_version_checkOperationCompleted = new System.Threading.SendOrPostCallback(this.Onbarcode_version_checkOperationCompleted);
            }
            this.InvokeAsync("barcode_version_check", new object[0], this.barcode_version_checkOperationCompleted, userState);
        }
        
        private void Onbarcode_version_checkOperationCompleted(object arg) {
            if ((this.barcode_version_checkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.barcode_version_checkCompleted(this, new barcode_version_checkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/product_get", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string product_get(string serial) {
            object[] results = this.Invoke("product_get", new object[] {
                        serial});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void product_getAsync(string serial) {
            this.product_getAsync(serial, null);
        }
        
        /// <remarks/>
        public void product_getAsync(string serial, object userState) {
            if ((this.product_getOperationCompleted == null)) {
                this.product_getOperationCompleted = new System.Threading.SendOrPostCallback(this.Onproduct_getOperationCompleted);
            }
            this.InvokeAsync("product_get", new object[] {
                        serial}, this.product_getOperationCompleted, userState);
        }
        
        private void Onproduct_getOperationCompleted(object arg) {
            if ((this.product_getCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.product_getCompleted(this, new product_getCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/product_out", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string product_out(string serial, string outdate, string to_location, string out_name) {
            object[] results = this.Invoke("product_out", new object[] {
                        serial,
                        outdate,
                        to_location,
                        out_name});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void product_outAsync(string serial, string outdate, string to_location, string out_name) {
            this.product_outAsync(serial, outdate, to_location, out_name, null);
        }
        
        /// <remarks/>
        public void product_outAsync(string serial, string outdate, string to_location, string out_name, object userState) {
            if ((this.product_outOperationCompleted == null)) {
                this.product_outOperationCompleted = new System.Threading.SendOrPostCallback(this.Onproduct_outOperationCompleted);
            }
            this.InvokeAsync("product_out", new object[] {
                        serial,
                        outdate,
                        to_location,
                        out_name}, this.product_outOperationCompleted, userState);
        }
        
        private void Onproduct_outOperationCompleted(object arg) {
            if ((this.product_outCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.product_outCompleted(this, new product_outCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/product_check_tolocation", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string product_check_tolocation(string product, string serial, string fromlocation, string what) {
            object[] results = this.Invoke("product_check_tolocation", new object[] {
                        product,
                        serial,
                        fromlocation,
                        what});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void product_check_tolocationAsync(string product, string serial, string fromlocation, string what) {
            this.product_check_tolocationAsync(product, serial, fromlocation, what, null);
        }
        
        /// <remarks/>
        public void product_check_tolocationAsync(string product, string serial, string fromlocation, string what, object userState) {
            if ((this.product_check_tolocationOperationCompleted == null)) {
                this.product_check_tolocationOperationCompleted = new System.Threading.SendOrPostCallback(this.Onproduct_check_tolocationOperationCompleted);
            }
            this.InvokeAsync("product_check_tolocation", new object[] {
                        product,
                        serial,
                        fromlocation,
                        what}, this.product_check_tolocationOperationCompleted, userState);
        }
        
        private void Onproduct_check_tolocationOperationCompleted(object arg) {
            if ((this.product_check_tolocationCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.product_check_tolocationCompleted(this, new product_check_tolocationCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/product_check", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string product_check(string product, string serial, string fromlocation, string what) {
            object[] results = this.Invoke("product_check", new object[] {
                        product,
                        serial,
                        fromlocation,
                        what});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void product_checkAsync(string product, string serial, string fromlocation, string what) {
            this.product_checkAsync(product, serial, fromlocation, what, null);
        }
        
        /// <remarks/>
        public void product_checkAsync(string product, string serial, string fromlocation, string what, object userState) {
            if ((this.product_checkOperationCompleted == null)) {
                this.product_checkOperationCompleted = new System.Threading.SendOrPostCallback(this.Onproduct_checkOperationCompleted);
            }
            this.InvokeAsync("product_check", new object[] {
                        product,
                        serial,
                        fromlocation,
                        what}, this.product_checkOperationCompleted, userState);
        }
        
        private void Onproduct_checkOperationCompleted(object arg) {
            if ((this.product_checkCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.product_checkCompleted(this, new product_checkCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/product", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string product([System.Xml.Serialization.XmlElementAttribute("product")] string product1, string serial, string fromlocation, string what) {
            object[] results = this.Invoke("product", new object[] {
                        product1,
                        serial,
                        fromlocation,
                        what});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void productAsync(string product1, string serial, string fromlocation, string what) {
            this.productAsync(product1, serial, fromlocation, what, null);
        }
        
        /// <remarks/>
        public void productAsync(string product1, string serial, string fromlocation, string what, object userState) {
            if ((this.productOperationCompleted == null)) {
                this.productOperationCompleted = new System.Threading.SendOrPostCallback(this.OnproductOperationCompleted);
            }
            this.InvokeAsync("product", new object[] {
                        product1,
                        serial,
                        fromlocation,
                        what}, this.productOperationCompleted, userState);
        }
        
        private void OnproductOperationCompleted(object arg) {
            if ((this.productCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.productCompleted(this, new productCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/login", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string login(string id, string pwd) {
            object[] results = this.Invoke("login", new object[] {
                        id,
                        pwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string id, string pwd) {
            this.loginAsync(id, pwd, null);
        }
        
        /// <remarks/>
        public void loginAsync(string id, string pwd, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        id,
                        pwd}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void HelloWorldCompletedEventHandler(object sender, HelloWorldCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class HelloWorldCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal HelloWorldCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void tokenCompletedEventHandler(object sender, tokenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tokenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tokenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void potal_version_checkCompletedEventHandler(object sender, potal_version_checkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class potal_version_checkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal potal_version_checkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void barcode_version_checkCompletedEventHandler(object sender, barcode_version_checkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class barcode_version_checkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal barcode_version_checkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void product_getCompletedEventHandler(object sender, product_getCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product_getCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal product_getCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void product_outCompletedEventHandler(object sender, product_outCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product_outCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal product_outCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void product_check_tolocationCompletedEventHandler(object sender, product_check_tolocationCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product_check_tolocationCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal product_check_tolocationCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void product_checkCompletedEventHandler(object sender, product_checkCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class product_checkCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal product_checkCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void productCompletedEventHandler(object sender, productCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class productCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal productCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.4084.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591